import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { BsCardImage } from "react-icons/bs";
import Footer from "../components/footer";
import { homedata } from "../data/homedata";

export default function Home() {
  const [activeLink, setActiveLink] = useState("All Work");
  const [homeData, setHomeData] = useState(homedata);

  const activeLinkHandler = (e) => {
    setActiveLink(e.target.textContent);
  };

  const hiddenHandler = (e) => {
    setHomeData((prev) => {
      let temp = [];
      prev.map((item) => {
        if (e.target.textContent === "All Work") {
          temp = [...temp, { ...item, isHidden: false }];
        } else if (item.type !== e.target.textContent) {
          temp = [...temp, { ...item, isHidden: true }];
        } else {
          temp = [...temp, { ...item, isHidden: false }];
        }
      });

      return temp;
    });
  };

  return (
    <div className="layout">
      <Head>
        <title>Vixniv - Hi there! 👋</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="thisisheader mt-14 mb-16 flex flex-col sm:flex-row sm:justify-between sm:items-end">
        <div className="sm:max-w-[80%] xl:max-w-[943px]">
          <h2 className="mb-8 text-sm">Hola!</h2>
          <h1 className="text-2xl mb-8 sm:mb-0">
            I&#39;m Yoram Amalian Arasy, <i>aka Vixniv</i>, a{" "}
            <span className="font-title">UX Designer</span> and{" "}
            <span className="font-title">Software Engineer</span> based in
            mostly sunny ☀ Jakarta, ID. Currently designing and developing for
            clients around the world.
          </h1>
        </div>
        <div className="flex flex-col items-center sm:flex-col-reverse">
          <div className="bg-secondary w-[84px] h-[81px] rounded-full relative mb-3 sm:mt-3">
            <Image
              src="/vixnivpp.jpg"
              alt="Profile Picture"
              layout="fill"
              objectFit="contain"
              className="rounded-full"
            />
          </div>
          <div>
            <Link href="/about">
              <a className="px-[10px] py-[5px] rounded-xl hover:bg-secondary">
                About me
              </a>
            </Link>
          </div>
        </div>
      </div>

      <div className="thisisnav mb-8 overflow-auto whitespace-nowrap sm:mb-11">
        <ul className="flex items-center">
          <li
            className={`navlink mr-3 ${
              activeLink == "All Work" ? "bg-primary" : ""
            }`}
            onClick={(e) => {
              activeLinkHandler(e);
              hiddenHandler(e);
            }}
          >
            All Work
          </li>
          <li
            className={`navlink mr-3 ${
              activeLink == "Design" ? "bg-primary" : ""
            }`}
            onClick={(e) => {
              activeLinkHandler(e);
              hiddenHandler(e);
            }}
          >
            Design
          </li>
          <li
            className={`navlink ${
              activeLink == "Development" ? "bg-primary" : ""
            }`}
            onClick={(e) => {
              activeLinkHandler(e);
              hiddenHandler(e);
            }}
          >
            Development
          </li>
        </ul>
      </div>

      <div className="thisiswork grid grid-cols-1 gap-y-10 gap-x-8 mb-60 sm:grid-cols-2 md:grid-cols-3">
        {homeData.map((item) => (
          <div
            className={`thisiscard flex flex-col ${
              item.isHidden ? "hidden" : ""
            }`}
            key={item.id}
          >
            <Link href={`/work/${item.url}`}>
              <div className="bg-secondary w-full h-full aspect-square rounded-[20px] flex justify-center items-center relative mb-4 cursor-pointer duration-300 hover:brightness-90">
                {item.image ? (
                  <Image
                    src={item.image}
                    alt="Profile Picture"
                    layout="fill"
                    className="rounded-[20px]"
                  />
                ) : (
                  item.icon
                  // <BsCardImage size={48} />
                )}
              </div>
            </Link>
            <div className="flex flex-col-reverse justify-between lg:flex-row">
              <div className="lg:max-w-[75%]">
                <Link href={item.url}>
                  <h3 className="text-2xl mb-[6px] cursor-pointer">
                    {item.title}
                  </h3>
                </Link>
                <p className="text-tertiary">{item.desc}</p>
              </div>
              <div className="mb-2">
                <h4
                  className={`px-[10px] py-[5px] rounded-xl font-bold inline-block ${
                    item.type === "Development"
                      ? "bg-[#DAA6FF]"
                      : "bg-[#C0EEFF]"
                  }`}
                >
                  {item.type}
                </h4>
              </div>
            </div>
          </div>
        ))}
      </div>

      <Footer />
    </div>
  );
}
