import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [activeLink, setActiveLink] = useState("All Work");

  const activeLinkHandler = (e) => {
    setActiveLink(e.target.textContent);
  };

  return (
    <div className="container mx-auto px-7 sm:px-0">
      <Head>
        <title>Vixniv - Hi there! 👋</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="thisisheader mt-14 mb-16 flex flex-col sm:flex-row sm:justify-between sm:items-end">
        <div className="sm:max-w-[80%] xl:max-w-[943px]">
          <h2 className="mb-8 text-sm">Hola!</h2>
          <h1 className="text-2xl mb-8 sm:mb-0">
            I&#39;m Yoram Amalian Arasy, <i>aka Vixniv</i>, a{" "}
            <span className="font-title">UX Designer</span> and{" "}
            <span className="font-title">Software Engineer</span> based in
            mostly sunny ☀ Jakarta, ID. Currently designing and developing for
            clients around the world.
          </h1>
        </div>
        <div className="flex flex-col items-center sm:flex-col-reverse">
          <div className="bg-secondary w-[84px] h-[81px] rounded-full relative mb-3 sm:mt-3">
            <Image
              src="/vixnivpp.jpg"
              alt="Profile Picture"
              width="100%"
              height="100%"
              layout="fill"
              objectFit="contain"
              className="rounded-full"
            />
          </div>
          <div>
            <Link href="/about">
              <a className="px-[10px] py-[5px] rounded-xl hover:bg-secondary">
                About me
              </a>
            </Link>
          </div>
        </div>
      </div>

      <div className="thisisnav">
        <ul className="flex items-center">
          <li
            className={`navlink mr-3 ${
              activeLink == "All Work" ? "bg-primary" : ""
            }`}
            onClick={activeLinkHandler}
          >
            All Work
          </li>
          <li
            className={`navlink mr-3 ${
              activeLink == "Design" ? "bg-primary" : ""
            }`}
            onClick={activeLinkHandler}
          >
            Design
          </li>
          <li
            className={`navlink ${
              activeLink == "Development" ? "bg-primary" : ""
            }`}
            onClick={activeLinkHandler}
          >
            Development
          </li>
        </ul>
      </div>
    </div>
  );
}
